src/screens/lyrics.cpp
src/utility/string.cpp
src/utility/string.h

Fixes #345.
I removed the `/bin/sh -c` part of the command for convenience and because it seemed superfluous, but is there some rationale for it that I'm not aware of?

Pass lyrics filename in single quotes

---

src/actions.cpp
src/actions.h

Right now sending the 'pause/resume' command to MPD if you are in the stopped state won't do anything, which is annoying since you have to switch to the playlist first.
With the 'play' action you can now do something like
```
def_key "space"
pause
def_key "space"
play
```
, and have a single keybinging for resuming or starting playing. Hopefully this is ok!
This would probably resolve https://github.com/arybczak/ncmpcpp/issues/197 as well.

Add support for starting playback in stopped state

---

src/configuration.cpp

Hello! This makes the tilda expand when mpd_host has both a password and points to a file: 'password@~/.mpd/socket'.

Expand '~' in mpd_host when preceded by a password.

---

README.md

Even though I used ncmpcpp for a long time, after installing it on a new computer, I struggled for hours trying to find how to enable the visualizer. And also found many users across many forums asking the same. 
I thought it would be helpful if it is right here in the readme. Most of the file's contents are from [here](http://rybczak.net/ncmpcpp/). Added markdown for decoration and specified the example options.

Add a README, showing enable visualizer

---

doc/config
doc/ncmpcpp.1
src/settings.cpp
src/settings.h
src/status.cpp

I added the ability to not display the "Connected to ..." message at startup.
It can be annoying if you close and reopen multiple times ncmpcpp.

Add ability to not display the "Connected to ..." message at startup

---

src/curses/window.cpp
src/curses/window.h
src/screens/help.cpp

On DirectColor-capable terminals with the proper terminfo
database in use, COLORS is 2^24. Since the color map is
only 64k entries, this resulted in a segfault. I've
introduced NC::colorCount(), which bounds it by the
previously assumed maximum (and usable range) of 256.

Curses: don't iterate through unbound COLORS #369

---

src/tags.cpp

This will fix https://github.com/arybczak/ncmpcpp/issues/371
taglib deprecated removeField internally in [1], but did not add the
deprecation warning until about four years later. The original bug
report [2] and pull request commit both mention not wanting to change
the original method's behaviour, but this was done anyway (perhaps by
mistake) in [3].
With that change, removeField(type) will not remove all tags of the
given type anymore, as the default for value has changed from
String::null to String().
This commit replaces explicit calls to removeField(type) with
removeFields(type), which has the correct behaviour. In writeXiph,
removeField is removed entirely, as addField(key, value) will replace
the tag by default.
[1] https://github.com/taglib/taglib/pull/681
[2] …

Stop using deprecated removeField method

---

src/mpdpp.h

Hi
This fixes the following error that appeared when building with GCC 10:
```
./mpdpp.h: In constructor ‘MPD::Playlist::Playlist(std::string, time_t)’:
./mpdpp.h:182:15: error: ‘runtime_error’ is not a member of ‘std’
182 |    throw std::runtime_error("empty path");
|               ^~~~~~~~~~~~~
```

Fix build with GCC 10 by adding missing include

---

src/curses/window.cpp

There is a bug where the delete key doesn't work in [st](https://st.suckless.org/). This is because of an escape sequence it uses to delete, namely ^[[P. This PR simply adds that escape sequence to the list of escape sequences.
fixes #424

Fix delete key in st

---

src/actions.cpp
src/actions.h

The `Add` command only falls back to a playlist load if mpd returns a specific error code for the add command. This is currently the only way to load a playlist via ncmpcpp and is suboptimal for a few reasons. It also gets in the way when mpd playlist and input plugins exist that handle the same URL scheme. mpd's maintainer has [previously commented on this behaviour](https://github.com/MusicPlayerDaemon/MPD/pull/223#discussion_r168917342), calling it:
> funny assumptions on something that's not explicitly documented in the protocol spec (and yes, the protocol spec isn't very specific on some things, and needs to improve).
This PR adds an explicit playlist load command to be used when the user wants to add a playlist instead. Note that this PR does not include a default keybinding for the …

Add an explicit playlist Load action

---

Makefile.am

With [`d1fe67b0314759f39560031d93c337ae997e8504`](https://github.com/ncmpcpp/ncmpcpp/commit/d1fe67b0314759f39560031d93c337ae997e8504), building from master would fail: `make[2]: *** No rule to make target 'NEWS', needed by 'all-am'.  Stop.`.

Update Makefile to reflect NEWS-->CHANGELOG.md rename

---

AUTHORS
CHANGELOG.md
doc/config
doc/ncmpcpp.1
src/settings.cpp

Although this can already be set via mpd_host, having a separate option
is cleaner, and doesn't require setting the host when ncmpcpp already
detects it correctly.

configuration: add mpd_password option

---

src/tags.cpp

- fixes a bug where editing Vorbis comment doesn't support multiple values.
To reproduce: open tag editor, change some field of a FLAC or Ogg Vorbis file to contain multiple values, save. Now only the last value is saved.
- adds Vorbis comment support for Opus.

Fix vorbis comment and add support for Opus

---

src/actions.cpp
src/curses/window.cpp

* In #259 users request the ability to have ncmpcpp remain open when the
terminal has a small size. Previously ncmpcpp would exit when there
were less than 30 columns or 5 rows.
* After removing this constraint, ncmpcpp would freeze when terminal
sizes went below those thresholds.
* Upon debugging, it became clear that ncmpcpp wasn't frozen, it was
stuck in a very long for loop because it thought the display was
unreasonably large (resulting from integer overflow).
* Preventing that overflow allows ncmpcpp to handle small sizes
gracefully. No other changes to the rendering code were necessary.
Fixes #259

Fix overflow errors and allow small terminal sizes

---

CHANGELOG.md
src/display.cpp

Fixes the separator between albums of the same name introduced in [`89ebfbf`](https://github.com/ncmpcpp/ncmpcpp/commit/89ebfbf73dbf68221de4e735ea75c4e7a4a7bf10), as it visually splits up an album if the artist changes. Which means that every track with a feature get a separator above and below:
I changed the check to compare album artists instead, which are consistent across the whole album.
fixes #455

Fix separator between albums with the same name

---

src/settings.cpp

I changed the maximum fps limit from 144 to 1000. I have a 240Hz monitor and today 360Hz monitors are consumer level tech available on the market.
As time goes on monitor refresh rates will keep getting higher and higher so changing this limit to 1000 should be enough for now.

Increase the framerate limit for the visualizer.

---

src/tags.cpp

Fixes issue https://github.com/ncmpcpp/ncmpcpp/issues/468.
Why: mpd recently [changed](https://github.com/MusicPlayerDaemon/MPD/pull/1079/files) its tag definitions, causing a mismatch against ncmpcpp's.  
- Previously, "Performer" could be either TPE3 or TPE4
- Now, TPE3 is assigned to "Conductor" instead (in compliance with the ID3 [standard](https://id3.org/id3v2.3.0))
What: updates definitions to match mpd's, so ncmpcpp can read and write the "Performer" tag without issues.
Haven't tested.

Bugfix: read Performer ID3 tag from TPE4, not TPE3

---

src/screens/playlist_editor.cpp

Fixes #559, also fixes #539 and fixes #521.
The referenced issue occurs here (Presumably, the unresponsiveness occurs due to the playlist not being properly resized. Regardless, ensuring that the resizing does happen even after an error occurs seems to solve this).
https://github.com/ncmpcpp/ncmpcpp/blob/417d7172e5587f4302f92ea6377268dca7f726ad/src/screens/playlist_editor.cpp#L170-L180
The error code received in the issue is `MPD_SERVER_ERROR_UNKNOWN_CMD`, which fails the if statement, and thus the code throws the error.
The problem here is throwing leaves the remaining code outside of the catch block (which handles the case where the playlist might not have been iterated through fully) unreachable.
The code already appears to be trying to handle `MPD_SERVER_ERROR_SYSTEM` (which in that …

Fix unresponsive stall when server error occurs

---

src/curses/window.cpp

Terminals that don't restore the terminal state when a program exits (wezterm) display `stdin` incorrectly after quitting. Fixed by saving and restoring the terminal state with `termios`. This is not a bug in `readline.h` as its examples use `termios` in the same way.

Fixed bug related to readline.h

---

configure.ac

When trying to build the project, I encounter several errors at the very first step - about obsolete autoconf macros.

fix: update obsolete macros in autoconf

---

src/screens/lyrics.cpp
src/song.cpp

When `fetch_lyrics_for_current_song_in_background` is set to `yes`, and an HTTP(S) stream is loaded with a long URL, ncmpcpp crashes due to the length of the filename generated to store lyrics. This PR makes the background lyrics fetcher ignore such streams, preventing the crash. Addresses issue #380. Replaces #541; this PR pulls from a specific branch instead of master.
For HTTP(S) streams, `Lyrics::fetchInBackground` makes ncmpcpp crash: the `lyrics_file` gets set to the stream URL, which is too long, hence `boost::filesystem::exists()` fails.
To reproduce the crash
1. Ensure `ncmpcpp` is not running
2. Queue a stream with a long URL in MPD, I use `mpc add "$(yt-dlp -x -g 'https://www.youtube.com/watch?v=DZnDeEjM6j8')"`
* `yt-dlp` generates a long URL such as …

Fix crash when background-fetching lyrics for streams

---

configure.ac

Programs like taglib-config are not good when cross-compiling.

Check for taglib with pkg-config before trying taglib-config

---

doc/config
doc/ncmpcpp.1
src/screens/visualizer.cpp
src/screens/visualizer.h
src/settings.cpp
src/settings.h

I replaced the previous flipping method with chars I found in [Symbols for Legacy Computing](https://unicode.org/charts/PDF/U1FB00.pdf). This improves the spectrum visualizer when viewed in a terminal with a transparent background.
old:
new:
(Both tested in kitty)

Improve specrum visulaizer for transparent backgrounds

---

doc/config
src/screens/visualizer.cpp
src/screens/visualizer.h
src/settings.cpp
src/settings.h

Brings back the linear(-ish) axis scaling from pre-0.9.x (see #453) while keeping DFT adjustments made in #397 and adding config options `visualizer_spectrum_log_scale_x` and `visualizer_spectrum_log_scale_y` for log scaling on either/both axes.
Also switches the character used for the sound ellipse to `Config.visualizer_chars[0]` from `Config.visualizer_chars[1]` (by default this is the round character rather than the bar) because I thought it looked silly otherwise.
Here's a sample of what the linear scaling looks like in my terminal:
and with `visualizer_smooth_look = yes`:
A couple additional notes:
- I noticed that the cubic interpolation used with log-scaling caused a problem when linear-scaling where the leftmost column would not be cropped properly and instead wrap onto the …

Tweaks to frequency spectrum and sound ellipse in visualizer
